### PR TITLE
about log

### PR DESCRIPTION
**Pull request by Wyatt-rodriguez**
I got error no module in tensorflow.python.keras.utils while i tried to  get params from param.py
here is my code with log in TF_Model.ipynb
can I get some help?

### CODE REVIEW

**Comment by CNTBMS** [comment]
which version of python did you installed?

**Comment by CNTBMS** [comment]
which version of python and tensorflow  you installed?

**Comment by Wyatt-rodriguez** [comment]
@CNTBMS python == 3.7 and tensorflow == 2.0.3

**Comment by CNTBMS** [comment]
you should replace import module line
from
`from tensorflow.python.keras.utils import layer_utils`
to
`from keras.utils.layer_utils import count_params`
layer_utils operates in newer tensorflow
you can use count_params() instead of layer_utils in old version

**Comment by Wyatt-rodriguez** [comment]
thx, it works

**Pull request merged**
